# version of docker-compose 
version: '3.9'
services:
  # add server
  server:
  # location to server dockerfile
    build: 
      context: ./server 
      # name of dockerfile 
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      # Host port: container port 
      - '4000:4000'
    volumes:
      # bind-mounts configuration
      - ./server:/app
      # ignore any changes made in "node_modules"
      - ./app/node_modules
  client1: 
  # location to client dockerfile
    build:
      context: ./client
      # name of dockerfile
      dockerfile: Dockerfile
    container_name: client-container
    volumes:
      - ./client:/app
      - ./app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
